name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Inject GitHub Token Into Settings
      run: |
          sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' .m2/settings.xml
          cat .m2/settings.xml
      env:
          GITHUB_TOKEN: ${{secrets.add_git}}
          
    - name: Build with Maven
      run: mvn -B -DskipTests clean package
    - name: Run Maven Tests
      run: mvn test
    - name: Publish Maven Artifacts
      run: mvn deploy --settings .m2/settings.xml
